import { UAppTheme, UColorScheme } from "sleek-ui/app-theme.slint";
import { UText, UTitle, UButton } from "sleek-ui/widgets.slint";
import "Fonts/Asimovian-Regular.ttf";
import "Fonts/Kanit-Light.ttf";
import { VerticalBox } from "std-widgets.slint";

export component SideBar inherits Rectangle {
    in property <length> sidebar_width: 150px;
    in property <length> sidebar_height: 600px;
    in property <length> sidebar_btwidth: 125px;
    in property <length> sidebar_btheight: 35px;
    in property <length> sidebar_btspace: 8px;

    in property <color> sidebar_btcolor: rgb(30,0,105);
    in property <color> sidebar_bthovercolor: rgb(30,0,55);

    in property <color> sidebar_bgcolor: rgb(1,4,30);
    in property <[string]> menu_items: ["Home", "Settings", "Pricer"];
    in property <int> active_item: 0;

    callback item_selected(int, string);

    width: sidebar_width;
    height: sidebar_height;
    background: sidebar_bgcolor; 

    VerticalBox {
        alignment: start;
        spacing: sidebar_btspace;
        padding: 15px;

        for item[index] in root.menu_items : UButton {
            text: item;
            variant: primary;
            background: index == root.active_item ? rgb(60, 20, 140) : sidebar_btcolor;
            horizontal-stretch: 1;
            
            width: sidebar_btwidth;
            height: sidebar_btheight;

            clicked => {
                root.item_selected(index, item);
            }
        }
    }
}